
language: c
dist: xenial
os: linux

env:
  global:
    - MAKEFLAGS="-j 2"

git:
  depth: 200    # to make sure we find the latest tag when building. Increase if not enough.

addons:
  apt:
    sources:
    - sourceline: "deb https://apt.kitware.com/ubuntu/ xenial main"
      key_url: "https://apt.kitware.com/keys/kitware-archive-latest.asc"
    packages:
    - cmake
    - flex
    - bison
    - docbook2x
    - xmlto
    - texinfo
    - source-highlight
    - libxml2-utils
    - xsltproc
    - fop
    - libgmp-dev
    - libglpk-dev
    - libarpack2-dev
    - libblas-dev
    - liblapack-dev
    - git
  homebrew:
    packages:
    - flex
    - bison
    - gmp
    - glpk

script:
  - make check

after_failure:
  - find tests/testsuite.dir -name testsuite.log -exec cat \{\} \;

jobs:
  include:
    - name: "Linux"
      os: linux
      install:
        - mkdir build
        - cd build
        - /usr/bin/cmake .. -DIGRAPH_USE_INTERNAL_BLAS=1 -DIGRAPH_USE_INTERNAL_LAPACK=1 -DIGRAPH_USE_INTERNAL_ARPACK=1 -DIGRAPH_USE_INTERNAL_GLPK=1 -DIGRAPH_USE_INTERNAL_CXSPARSE=1 -DIGRAPH_VERIFY_FINALLY_STACK=1
        - make
    - name: "Linux external deps"
      os: linux
      dist: bionic
      install:
        - mkdir build
        - cd build
        - /usr/bin/cmake .. -DIGRAPH_VERIFY_FINALLY_STACK=1
        - make
    - name: "Linux x87"
      os: linux
      env:
        - CFLAGS="-mfpmath=387" CXXFLAGS="-mfpmath=387"
      install:
        - mkdir build
        - cd build
        - /usr/bin/cmake .. -DCMAKE_VERBOSE_MAKEFILE=1

    - name: "macOS"
      os: osx
      osx_image: xcode11.5    # we need a newer CMake in the image
      install:
        - mkdir build
        - cd build
        - cmake .. -DIGRAPH_USE_INTERNAL_BLAS=1 -DIGRAPH_USE_INTERNAL_LAPACK=1 -DIGRAPH_USE_INTERNAL_ARPACK=1 -DIGRAPH_USE_INTERNAL_GLPK=1 -DIGRAPH_USE_INTERNAL_CXSPARSE=1 -DIGRAPH_VERIFY_FINALLY_STACK=1 -DUSE_SANITIZER=Address\;Undefined
        - make

    - name: "Documentation"
      language: shell
      os: linux
      install:
        - mkdir build
        - cd build
        - /usr/bin/cmake ..
      script:
        - make doc

notifications:
  email:
    on_success: change
    on_failure: always
