name: Bug report
description: Report a problem in the igraph C library
labels: "bug :beetle:"
body:

- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: To reproduce
    description: Steps or minimal example code to reproduce the problem.
  validations:
    required: true

- type: input
  attributes:
    label: Version information
    description: Which version of igraph are you using?
  validations:
    required: true

- type: textarea
  attributes:
    label: Where did you obtain igraph?
    description: Describe how did you obtain and install igraph. Examples:
      standard OS package manager, pre-compiled binary from third-party
      package repository, or compiled on your own
